---
version: '3.8'

services:
  django:
    build:
      context: ../
      dockerfile: ./docker/dockerfile/Dockerfile.django
    image: ${PROJECT_NAME}_dj
    container_name: dj
    restart: always
    depends_on:
      - database
      - redis
    ports:
      - target: 8000
        published: ${DD_PORT:-8000}
        protocol: tcp
        mode: host
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DATABASE_URL: ${DATABASE_URL}
      DYNAMO_AWS_REGION: ${DYNAMO_AWS_REGION}
      DYNAMO_AWS_ACCESS_KEY_ID: ${DYNAMO_AWS_ACCESS_KEY_ID}
      DYN${PROJECT_NAME}AMO_AWS_SECRET_ACCESS_KEY: ${DYNAMO_AWS_SECRET_ACCESS_KEY}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_URL: ${REDIS_URL}
      CACHEOPS_REDIS: ${CACHEOPS_REDIS}p

  database:  #Si modificas este valor, debes modificar el var.sh
    image: postgres:14.3
    container_name: db
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    restart: always
    volumes:
      - data-postgres:/var/lib/postgresql/data
  
  redis:
    image: redis:6.2.7
    container_name: redis

volumes:
  data-postgres: {} #Si modificas este valor, debes modificar el var.sh
#  data-pgadmin: {}